name: Check Pull Request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - staging
      - test
      - develop

jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      - uses: actions/cache@v2.1.3
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install
        run: npm ci
      - name: codegen
        run: npm run codegen
        env:
          REACT_APP_API: ${{ secrets.REACT_APP_API }}
          SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}

      - name: test
        run: npm test
        env:
          CI: ${{ secrets.CI }}
          REACT_APP_API: ${{ secrets.REACT_APP_API }}
          SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}

      - name: typecheck
        run: npm run type-check
        env:
          REACT_APP_API: ${{ secrets.REACT_APP_API }}
          SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}

      - name: lint
        run: npm run lint
        env:
          REACT_APP_API: ${{ secrets.REACT_APP_API }}
          SCHEMA_PATH: ${{ secrets.SCHEMA_PATH }}
